### ISSUE TITLE
leaflet_map: Labels don't disappear on ie11

### ISSUE THREAD

**Issue by ateucher** [bcgov/roadless-areas-indicator#5]
When moving between polygons hover labels don't disappear; similarly they stay in view when popUps appear.

**Comment by stephhazlitt** [comment]
Similar issue with multiple browsers (Safari, DuckDuckGo, Chrome) on mobile devices.

**Comment by ateucher** [comment]
This is a known leaflet label issue: https://github.com/Leaflet/Leaflet.label/issues/114. Also doesn't look like there's an easy solution... :(

**Comment by ateucher** [comment]
I enabled the 'Reset Map' button to close all open labels, which I think is as close as we're going to get.
